
expected '<h1 id="hi">Hi!</h1>\n<h2 id="welcome-to-my-react-previewer">Welcome to my React previewer</h2>\n<p>Heres some code, <code>&lt;div&gt;&lt;/div&gt;</code>, between 2 backticks.</p>\n<pre><code>// this is multi-line code:\n\nfunction anotherExample(firstLine, lastLine) {\n  if (firstLine == \'```\' &amp;&amp; lastLine == \'```\') {\n    return multiLineCode;\n  }\n}</code></pre><p>You can also make text <strong>bold</strong><br>Or <em>italic</em>.\nOr <strong><em>both!</em></strong><br>And  <del>cross stuff out</del> if you want to.</p>\n<p>There\'s also <a href="https://codepen.io/bmansk14/">links</a>, and</p>\n<blockquote>\n<p>Block Quotes</p>\n</blockquote>\n<ul>\n<li>And of course there are lists.<ul>\n<li>Some are bulleted.<ul>\n<li>With different indentation levels.<ul>\n<li>That look like this.</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n<ol>\n<li>And there are numbererd lists too.</li>\n<li>Use just 1s if you want! </li>\n<li>But the list goes on...</li>\n</ol>\n<ul>\n<li>Even if you use dashes or asterisks.</li>\n<li>And last but not least, let\'s not forget embedded images:</li>\n</ul>\n<p><img src="https://goo.gl/Umyytc" alt="React Logo w/ Text"></p>\n' to equal '<h1 id="hi">Hi!</h1>\n<h2 id="welcome-to-my-react-previewer">Welcome to my React previewer</h2>\n<p>Heres some code, <code>&lt;div&gt;&lt;/div&gt;</code>, between 2 backticks.</p>\n<pre><code>// this is multi-line code:\n\nfunction anotherExample(firstLine, lastLine) {\n  if (firstLine == \'```\' &amp;&amp; lastLine == \'```\') {\n    return multiLineCode;\n  }\n}</code></pre><p>You can also make text <strong>bold</strong><br>Or <em>italic</em>.\nOr <strong><em>both!</em></strong><br>And  <del>cross stuff out</del> if you want to.</p>\n<p>There\'s also <a target="_blank" href="https://codepen.io/bmansk14/">links</a>, and</p>\n<blockquote>\n<p>Block Quotes</p>\n</blockquote>\n<ul>\n<li>And of course there are lists.<ul>\n<li>Some are bulleted.<ul>\n<li>With different indentation levels.<ul>\n<li>That look like this.</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n<ol>\n<li>And there are numbererd lists too.</li>\n<li>Use just 1s if you want! </li>\n<li>But the list goes on...</li>\n</ol>\n<ul>\n<li>Even if you use dashes or asterisks.</li>\n<li>And last but not least, let\'s not forget embedded images:</li>\n</ul>\n<p><img src="https://goo.gl/Umyytc" alt="React Logo w/ Text"></p>\n'
expected '<h1 id="hi">Hi!</h1>\n<h2 id="welcome-to-my-react-previewer">Welcome to my React previewer</h2>\n<p>Heres some code, <code>&lt;div&gt;&lt;/div&gt;</code>, between 2 backticks.</p>\n<pre><code>// this is multi-line code:\n\nfunction anotherExample(firstLine, lastLine) {\n  if (firstLine == \'```\' &amp;&amp; lastLine == \'```\') {\n    return multiLineCode;\n  }\n}</code></pre><p>You can also make text <strong>bold</strong><br>Or <em>italic</em>.\nOr <strong><em>both!</em></strong><br>And  <del>cross stuff out</del> if you want to.</p>\n<p>There\'s also <a href="https://codepen.io/bmansk14/">links</a>, and</p>\n<blockquote>\n<p>Block Quotes</p>\n</blockquote>\n<ul>\n<li>And of course there are lists.<ul>\n<li>Some are bulleted.<ul>\n<li>With different indentation levels.<ul>\n<li>That look like this.</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n<ol>\n<li>And there are numbererd lists too.</li>\n<li>Use just 1s if you want! </li>\n<li>But the list goes on...</li>\n</ol>\n<ul>\n<li>Even if you use dashes or asterisks.</li>\n<li>And last but not least, let\'s not forget embedded images:</li>\n</ul>\n<p><img src="https://goo.gl/Umyytc" alt="React Logo w/ Text"></p>\n' to equal '<h1 id="hi">Hi!</h1>\n<h2 id="welcome-to-my-react-previewer">Welcome to my React previewer</h2>\n<p>Heres some code, <code>&lt;div&gt;&lt;/div&gt;</code>, between 2 backticks.</p>\n<pre><code>// this is multi-line code:\n\nfunction anotherExample(firstLine, lastLine) {\n  if (firstLine == \'```\' &amp;&amp; lastLine == \'```\') {\n    return multiLineCode;\n  }\n}</code></pre><p>You can also make text <strong>bold</strong><br>Or <em>italic</em>.\nOr <strong><em>both!</em></strong><br>And  <del>cross stuff out</del> if you want to.</p>\n<p>There\'s also <a target="_blank" href="https://codepen.io/bmansk14/">links</a>, and</p>\n<blockquote>\n<p>Block Quotes</p>\n</blockquote>\n<ul>\n<li>And of course there are lists.<ul>\n<li>Some are bulleted.<ul>\n<li>With different indentation levels.<ul>\n<li>That look like this.</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n</li>\n</ul>\n<ol>\n<li>And there are numbererd lists too.</li>\n<li>Use just 1s if you want! </li>\n<li>But the list goes on...</li>\n</ol>\n<ul>\n<li>Even if you use dashes or asterisks.</li>\n<li>And last but not least, let\'s not forget embedded images:</li>\n</ul>\n<p><img src="https://goo.gl/Umyytc" alt="React Logo w/ Text"></p>\n'







=>
===
